"""Run-artifact writer tests."""

from __future__ import annotations

from pathlib import Path

import pytest

from gtmos.runs import RunArtifact


def test_writes_top_level_artifact(tmp_repo: Path) -> None:
    art = RunArtifact(
        agent="weekly-review",
        repo_root=tmp_repo,
        task="kai",
        inputs={"client": "acme", "owner": "kai"},
        output_text="All caught up. 3 shipped, 1 slipped.",
    )
    path = art.write()
    assert path.is_file()
    assert path.parent.parent == tmp_repo / "runs"
    body = path.read_text(encoding="utf-8")
    assert "weekly-review" in body
    assert "Generated by `agents/weekly-review.md`" in body


def test_writes_per_client_artifact(tmp_repo: Path) -> None:
    (tmp_repo / "clients" / "acme" / "runs").mkdir(parents=True)
    art = RunArtifact(
        agent="weekly-review",
        repo_root=tmp_repo,
        client_slug="acme",
        task="weekly-review",
        inputs={"client": "acme"},
        output_text="acme is healthy",
    )
    path = art.write()
    assert path.is_file()
    expected_root = tmp_repo / "clients" / "acme" / "runs"
    assert path.parent.resolve() == expected_root.resolve()


def test_redacts_secrets_in_output(tmp_repo: Path) -> None:
    fake = "g" + "hp_" + ("Q" * 36)
    art = RunArtifact(
        agent="campaign-drafter",
        repo_root=tmp_repo,
        task="leak",
        output_text=f"Here is a token: {fake}",
    )
    path = art.write()
    text = path.read_text(encoding="utf-8")
    assert "<redacted>" in text
    assert fake not in text


def test_atomic_write_no_partial_on_failure(
    tmp_repo: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    art = RunArtifact(
        agent="weekly-review",
        repo_root=tmp_repo,
        task="boom",
        output_text="x",
    )

    def boom(*args: object, **kwargs: object) -> None:
        raise RuntimeError("disk full")

    monkeypatch.setattr("gtmos.runs.os.replace", boom)
    with pytest.raises(RuntimeError):
        art.write()
    # No leftover .md from a partial atomic move.
    runs = list((tmp_repo / "runs").rglob("*.md"))
    assert runs == []


def test_traversal_in_task_rejected(tmp_repo: Path) -> None:
    art = RunArtifact(
        agent="weekly-review",
        repo_root=tmp_repo,
        task="../../../etc/passwd",
        output_text="x",
    )
    # Bad chars are stripped, leaving a benign filename — verify it stays inside the repo.
    path = art.write()
    assert path.is_relative_to(tmp_repo.resolve())


def test_invalid_slug_in_artifact_rejected(tmp_repo: Path) -> None:
    from gtmos.security import InvalidSlugError, PathEscapeError

    art = RunArtifact(
        agent="weekly-review",
        repo_root=tmp_repo,
        client_slug="../escape",
        output_text="x",
    )
    with pytest.raises((InvalidSlugError, PathEscapeError)):
        art.write()
