"""Run-artifact writer — every agent run produces an auditable record.

Path layout:

    runs/<YYYY-MM-DD>/<agent>-<task>.md            (top-level routine runs)
    clients/<slug>/runs/<YYYY-MM-DD>-<routine>.md  (per-client routine runs)

All paths funnel through ``security.safe_join`` to prevent traversal.
"""

from __future__ import annotations

import datetime as dt
import json
import logging
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from gtmos.security import redact, safe_join, validate_slug

logger = logging.getLogger(__name__)


@dataclass
class RunArtifact:
    """In-memory record of a single agent run."""

    agent: str
    repo_root: Path
    started_at: dt.datetime = field(default_factory=lambda: dt.datetime.now(tz=dt.UTC))
    client_slug: str | None = None
    task: str | None = None
    inputs: dict[str, Any] = field(default_factory=dict)
    output_text: str = ""
    eval_score: float | None = None
    eval_passed: bool | None = None
    error: str | None = None
    extra: dict[str, Any] = field(default_factory=dict)

    def write(self) -> Path:
        """Render to markdown and persist atomically."""
        path = _resolve_path(self)
        path.parent.mkdir(parents=True, exist_ok=True)
        body = self._render()
        # Atomic write — temp + rename.
        tmp = path.with_suffix(path.suffix + ".tmp")
        tmp.write_text(body, encoding="utf-8")
        # Use os.replace through the indirection for test patching; equivalent
        # to ``tmp.replace(path)`` but the test suite monkey-patches it.
        os.replace(tmp, path)  # noqa: PTH105 — preserved for test patchability
        logger.info("run artifact written: %s", path.relative_to(self.repo_root))
        return path

    # ---- rendering ----------------------------------------------------------

    def _render(self) -> str:
        ended_at = dt.datetime.now(tz=dt.UTC)
        duration_s = (ended_at - self.started_at).total_seconds()
        eval_line = ""
        if self.eval_passed is not None:
            verdict = "pass" if self.eval_passed else "fail"
            score = "n/a" if self.eval_score is None else f"{self.eval_score:.2f}/10"
            eval_line = f"Eval: {verdict} ({score}). "

        lines: list[str] = [
            f"# Run — {self.agent}"
            + (f" — {self.client_slug}" if self.client_slug else "")
            + (f" — {self.task}" if self.task else ""),
            "",
            f"**Started:** {self.started_at.isoformat(timespec='seconds')}",
            f"**Ended:**   {ended_at.isoformat(timespec='seconds')}",
            f"**Duration:** {duration_s:.2f}s",
            "",
            "## Inputs",
            "",
            "```json",
            redact(json.dumps(self.inputs, indent=2, default=str, sort_keys=True)),
            "```",
            "",
            "## Output",
            "",
            redact(self.output_text or "_(no output)_"),
            "",
        ]
        if self.error:
            lines += [
                "## Error",
                "",
                "```",
                redact(self.error),
                "```",
                "",
            ]
        if self.extra:
            lines += [
                "## Extra",
                "",
                "```json",
                redact(json.dumps(self.extra, indent=2, default=str, sort_keys=True)),
                "```",
                "",
            ]
        lines += [
            "---",
            "",
            f"Generated by `agents/{self.agent}.md` at "
            f"{ended_at.isoformat(timespec='seconds')}. "
            f"{eval_line}"
            f"Run path: `{_relative_path(self).as_posix()}`",
            "",
        ]
        return "\n".join(lines)


def _resolve_path(run: RunArtifact) -> Path:
    """Return the absolute on-disk path for the artifact, validated against root."""
    safe_agent = _safe_filename_component(run.agent, "agent")
    date_str = run.started_at.strftime("%Y-%m-%d")
    if run.client_slug:
        slug = validate_slug(run.client_slug, allow_underscore_prefix=True)
        suffix = run.task or run.agent
        safe_task = _safe_filename_component(suffix, "task")
        return safe_join(
            run.repo_root,
            "clients",
            slug,
            "runs",
            f"{date_str}-{safe_task}.md",
        )

    safe_task = _safe_filename_component(run.task or "task", "task")
    return safe_join(
        run.repo_root,
        "runs",
        date_str,
        f"{safe_agent}-{safe_task}.md",
    )


def _relative_path(run: RunArtifact) -> Path:
    p = _resolve_path(run)
    try:
        return p.relative_to(run.repo_root.resolve())
    except ValueError:
        # Should not happen since safe_join enforces containment, but degrade
        # gracefully for the rendered preview.
        return p


_BAD_CHARS = set('/\\:*?"<>|\0\n\r\t')


def _safe_filename_component(value: str, label: str) -> str:
    if not isinstance(value, str) or not value:
        raise ValueError(f"{label} must be a non-empty string")
    cleaned = "".join(c for c in value if c not in _BAD_CHARS).strip()
    if not cleaned:
        raise ValueError(f"{label} reduced to empty after sanitization: {value!r}")
    return cleaned[:80]
